[package]
name = "rust_projecteuler_7"
version = "0.1.0"
authors = ["Aden King <adenking@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
